'use strict';
module.exports = function() {
	return {
		"jquery": "libs/jquery-1.8.3",
		"ept": "libs/ept_all",
		"lodash": "libs/lodash",
		"base": "libs/base",
		"masonry": "libs/masonry",
		"ko": "libs/knockout-3.2.0",
		"jquery.sAutocomplete":"libs/jquery.sAutocomplete",
		"d3": "libs/d3",
		"events": "libs/events",
		"when": "libs/when.js",
		"then": "libs/then.js",
		"utils": "libs/utils",
		"moment": "libs/moment",
		"echart": "libs/baidu-echarts",
		"template": "modules/template",
		"api": "modules/api",
		"form": "modules/form",
		"juicer": "libs/juicer",
		"jquery.ui": "libs/ui/jquery-ui-1.9.2.custom",
		"jquery.ui.draggable": "libs/ui/jquery-ui-draggable",
		"jquery.pagination": "modules/jquery.pagination",
		"jquery.ui.time": "libs/ui/jquery-ui-timepicker-addon",
		"jquery.unparam": "libs/jquery.unparam",
		"jquery.cookie": "libs/jquery.cookie",
		"jquery.serializeObject": "libs/jquery.serializeObject",
		"jquery.validation-locale": "libs/validation/i18n/jquery.validationEngine-zh-cn",
		"jquery.validation": "libs/validation/jquery.validationEngine",
		"jquery.spageCount": "libs/jquery.sPageCount",
		"jquery.pubsub": "libs/jquery.tinypubsub",
		"jquery.hashchange": "libs/jquery.ba-hashchange",
		"itip": "modules/itip",
		"showbox": "modules/showbox",
		"zdialogbox": "modules/zdialogbox",
		"jquery.taghandler": "libs/jquery.taghandler",
		"jquery.lightBox": "libs/jquery.lightbox-0.5",
		"jquery.sSwitcher": "libs/jquery.sSwitcher",
		"jquery.swaplist": "libs/z_swaplist",
		"jquery.multiselect": "libs/multiselect/jquery.multiselect.filter",
		"multiselect": "libs/multiselect/jquery.multiselect",
		"jquery.sCheckAll": "libs/jquery.sCheckAll",
		"jquery.dialog": "libs/jquery.dialog",
		"jquery.fineuploader": "libs/jquery.fineuploader-3.7.1"
	}
}()